package com.zhenai.channel_manager.moudel;

import java.io.Serializable;
import java.util.Date;

/**
 * Entity for table 'channel_zhenai.SpreadChannel*' generated by sborm
 * 
 * @author sborm
 * @date 2016-06-24 14:57:33
 */
public class SpreadChannel  implements Serializable {

	public static final long serialVersionUID = 7545980099929823860L;

	/**
	 * 字段属性
	 */
	private Integer channelId;
	private Integer ChannelTypeID;
	private String ChannelName;
	private String website;
	private String Comment;
	private String OrderSeed;
	private String channelpwd;
	private Integer status;
	private Integer FeeType;
	private String Staple1;
	private String Staple2;
	private Date createTime;
	private Date onTime;
	private Date offTime;
	private String position;
	private String resource;
	private Date updateTime;
	private Integer platform;
	private Integer ChannelType2;

	public SpreadChannel() {
	}

	public void setChannelId (Integer channelId) {
		this.channelId = channelId;
	}
	public Integer getChannelId () {
		return this.channelId;
	}
	public void setChannelTypeID (Integer ChannelTypeID) {
		this.ChannelTypeID = ChannelTypeID;
	}
	public Integer getChannelTypeID () {
		return this.ChannelTypeID;
	}
	public void setChannelName (String ChannelName) {
		this.ChannelName = ChannelName;
	}
	public String getChannelName () {
		return this.ChannelName;
	}
	public void setWebsite (String website) {
		this.website = website;
	}
	public String getWebsite () {
		return this.website;
	}
	public void setComment (String Comment) {
		this.Comment = Comment;
	}
	public String getComment () {
		return this.Comment;
	}
	public void setOrderSeed (String OrderSeed) {
		this.OrderSeed = OrderSeed;
	}
	public String getOrderSeed () {
		return this.OrderSeed;
	}
	public void setChannelpwd (String channelpwd) {
		this.channelpwd = channelpwd;
	}
	public String getChannelpwd () {
		return this.channelpwd;
	}
	public void setStatus (Integer status) {
		this.status = status;
	}
	public Integer getStatus () {
		return this.status;
	}
	public void setFeeType (Integer FeeType) {
		this.FeeType = FeeType;
	}
	public Integer getFeeType () {
		return this.FeeType;
	}
	public void setStaple1 (String Staple1) {
		this.Staple1 = Staple1;
	}
	public String getStaple1 () {
		return this.Staple1;
	}
	public void setStaple2 (String Staple2) {
		this.Staple2 = Staple2;
	}
	public String getStaple2 () {
		return this.Staple2;
	}
	public void setCreateTime (Date createTime) {
		this.createTime = createTime;
	}
	public Date getCreateTime () {
		return this.createTime;
	}
	public void setOnTime (Date onTime) {
		this.onTime = onTime;
	}
	public Date getOnTime () {
		return this.onTime;
	}
	public void setOffTime (Date offTime) {
		this.offTime = offTime;
	}
	public Date getOffTime () {
		return this.offTime;
	}
	public void setPosition (String position) {
		this.position = position;
	}
	public String getPosition () {
		return this.position;
	}
	public void setResource (String resource) {
		this.resource = resource;
	}
	public String getResource () {
		return this.resource;
	}
	public void setUpdateTime (Date updateTime) {
		this.updateTime = updateTime;
	}
	public Date getUpdateTime () {
		return this.updateTime;
	}
	public void setPlatform (Integer platform) {
		this.platform = platform;
	}
	public Integer getPlatform () {
		return this.platform;
	}
	public void setChannelType2 (Integer ChannelType2) {
		this.ChannelType2 = ChannelType2;
	}
	public Integer getChannelType2 () {
		return this.ChannelType2;
	}
}
